apiVersion: v1
kind: Pod
metadata:
  name: advanced-pod-demo
  labels:
    app: advanced-pod-demo
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app
      image: nginx:1.27
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
      volumeMounts:
        - name: cache
          mountPath: /cache
  volumes:
    - name: cache
      emptyDir: {}
