apiVersion: v1
kind: Namespace
metadata:
  name: controller-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-demo
  namespace: controller-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controller-demo
  template:
    metadata:
      labels:
        app: controller-demo
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
