apiVersion: v1
kind: Pod
metadata:
  name: highly-dangerous-pod
  namespace: hardened-env
spec:
  privileged: true
  containers:
  - name: root-shell
    image: alpine:latest
    securityContext:
      privileged: true
      runAsUser: 0
