apiVersion: v1
kind: Pod
metadata:
  name: container-environment-demo
spec:
  containers:
    - name: env-demo
      image: busybox:1.36
      command: ["sh", "-c", "env && sleep 3600"]
      env:
        - name: TRAINING_MODULE
          value: "2.3.2"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
