apiVersion: apps/v1
kind: Deployment
metadata:
  name: manage-workloads-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: manage-workloads-demo
  template:
    metadata:
      labels:
        app: manage-workloads-demo
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
